name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-1-18:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Env
      run: env

    - name: Install c-for-go
      run: |
         find ${GOTOOLDIR} -name "cgo"
         ls ${GOTOOLDIR}
         go mod download github.com/NVIDIA/go-nvml
         go get github.com/xlab/c-for-go
         go install github.com/xlab/c-for-go

    - name: Generate
      run: make

    - name: Test
      run: |
        cd pkg/rocm_smi
        go build
